### ISSUE TITLE
fcAPI Missing

### ISSUE THREAD

**Issue by ikriz** [Unity-Technologies/GenericFrameRecorder#1]
Where abouts can i find the definition of the fcAPI? It seems to be missing in the project at the moment :)

**Comment by Fuelo** [comment]
I have the same issue: 
EXRRecorder.cs(12,9): error CS0246: The type or namespace name `fcAPI' could not be found. Are you missing an assembly reference?

**Comment by jasonm-unity** [comment]
The file is located: Assets/UTJ/FrameCapturer/Scripts/Encoder/fcAPI.cs

That file appears only if you imported the released package as that package includes, temporarily, another project: FrameCapturer, which can be found  at https://github.com/unity3d-jp/FrameCapturer

This project contains experimental classes that do the integration of the two projects. If you have no need for FrameCapture's extra file types, simply remove from your project: Assets/UTJ/FrameCapturer.
