### ISSUE TITLE
Camera as RenderTexture can't render multiple camera using ViewportRect

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#10]
The recorder doesn't seem to take in count the viewport rect set to cameras, always render full screen cameras on top of the others.

**Comment by jasonm-unity** [comment]
seems to be a Unity regression occurring: camera rendering to a render texture is ignoring the "View port" rectangle settings. This was introduced post 2017.1.0b6.
