### ISSUE TITLE
MPeg recoding with FrameCapturer somtimes leads to zero byte size files.

### ISSUE THREAD

**Issue by jasonm-unity** [Unity-Technologies/GenericFrameRecorder#12]
Sometimes, when the recording is short (10-20 frames), the resulting mpeg file is invalid and of size zero.
Looks like the async encoding gets killed to agresively for the Recorder on end of recording session and the mpeg encoders queue of frames to encode does not get a chance to be written to disk.

**Comment by filibis** [comment]
Hi @jasonm-unity , you may also want to take a look at [this issue](https://github.com/unity3d-jp/FrameCapturer/issues/18) which might be related.
