### ISSUE TITLE
MPeg-4: Default Video Target Bitrate is too low for high res resolution

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#14]
As discussed, we should leave the value field as custom bitrate but also implement a quality drop down list (High, Medium, Low) which would adjust the bitrate automatically. 

Should we do that for Audio bitrate as well ?

**Comment by jasonm-unity** [comment]
this is a FrameCapturer issue.
Won't fix in FrameRecorder

**Comment by i-saint** [comment]
I will fix it.
