### ISSUE TITLE
RenderTexture without Source breaks the UI and crashes the recorder on StartRecording

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#17]
If the ImageGenerator is set to RenderTexture and there is no Source assign to the slot, the Console will start to print error on when we start recording:
Exception: No Render Texture object provided as source
NullReferenceException: Object reference not set to an instance of an object

The recorder crash, the UI is wipped while in play mode.
Once the user stopped the play mode, the UI comes back but the record button is disabled and the label shows "Stop Recording", we have to close the tab and re-open the recorder to have it back to its initial state.

**Comment by jasonm-unity** [comment]
From recorder window (not timeline), "start recording" button is disabled until config/settings are valid.

in both timeline and recorder window, you now see a warning message when config is incorrect.
