### ISSUE TITLE
Timeline: Recorder clip affect the game fps even if its not active

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#18]
I setup a timeline that start at 5 sec seconds and record for 1sec (end time at 6sec).
When entering play mode, the game fps is immediately affected by my recorder clip settings.
At the end of the recorder session, the game fps comes back as it should.

Using two recorder clips though, the backup fps that is used to restore the game fps at the end of the record session seems to be corrupted by another recorder clip causing the game fps to use one of the target fps from recorder clips once restored.

**Comment by jasonm-unity** [comment]
nop, that is as designed as to make sure 1st frame recorded is deterministic.
If first part  was variable fps, 1 st frame actually recorded would be random.

**Comment by JoelFortin** [comment]
the game fps doesn't seems to come back after the record session if I have two recorder clip in the same time line.
