### ISSUE TITLE
Road to release:  Cleanup folder naming / structure

### ISSUE THREAD

**Issue by CMI-AdamM** [Unity-Technologies/GenericFrameRecorder#2]
Recorder needs to entirely live under a single folder if possible so people can move/clean/manage it easily.  Currently it makes a 'Unity' and a 'UTJ' folder in the root which is not typical asset behavior

- Create a 'Recorder' root folder

- Rename the UTJ folder into something more obvious / clear and put that in the Recorder folder

**Comment by jasonm-unity** [comment]
note: UTJ is NOT part of the Recorder, it's a separate github project.
At the moment, I'm bundling it in for convenience.

**Comment by jasonm-unity** [comment]
moved everyting FrameRecorder related to /Assets/FrameRecorder
