### ISSUE TITLE
Timeline: Game resolution not backed up properly when using multiple recorder clips with different resolution

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#21]
Having one timeline that contains two recorder clips:
- RecorderClip1:
set to trigger at 3 sec and render for 1 sec (End = 4sec)
resolution set to 720p
target fps = 20
- RecorderClip2:
set to trigger at 5 sec and render for 1 sec (End = 6sec)
resolution set to 240p
target fps = 50

Current result:
Pressing Play, the game's resolution will be set to 240p with 50 fps for both recorder clips.
(we get a warning about fps conflicts and 50fps is being used ... that's expected and normal, multiple fps isn't supported anyway)

Expected result:
- The game resolution should adjust according the recorder clip that is playing.

**Comment by jasonm-unity** [comment]
fixed in alpha 1, build 8
