### ISSUE TITLE
Cannot build game

### ISSUE THREAD

**Issue by RealXaon** [Unity-Technologies/GenericFrameRecorder#22]
After importing GenericFrameRecorder.unitypackage from Alpha 1, build 7 I cannot build game due to compiler errors.
The errors are about using UnityEditor namespace.
Moving whole FrameRecorder into Editor folder does allow to build game but I haven't tested if there are other issues after.

The error logs are:
Assets/FrameRecorder/Core/Engine/RecordersInventory.cs(4,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
Assets/FrameRecorder/Inputs/CBRenderTexture/Engine/GameViewSize.cs(4,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
Assets/FrameRecorder/Inputs/CBRenderTexture/Engine/GameViewSize.cs(13,23): error CS0246: The type or namespace name `EditorWindow' could not be found. Are you missing an assembly reference?

My target platform is Android. I'm using Windows PC.

**Comment by jasonm-unity** [comment]
Thank you for reporting this, targetting platforms other than PC and MAC has need been tested yet.
I'll clean that up asap.
