### ISSUE TITLE
Video Player Assets frame rate issue

### ISSUE THREAD

**Issue by OpusJoyous** [Unity-Technologies/GenericFrameRecorder#29]
- Video player assets (activated from the timeline) are rendering out of sync when exporting an image sequence from the timeline.
(They play fine in the editor and game play preview. It seems that they are running on different frame rates than the export is running. Is there a way to sync them similar to the play mode?)

This is reproducible every time.
Using Recorder Version 2
Running WIndows 10, Unity 2017.1

**Comment by jasonm-unity** [comment]
That is a known limitation of Unity's video player: it does not support fixed frame rate playback on all platforms.
See: https://fogbugz.unity3d.com/f/cases/879946/

And such, this is not a recorder issue so I'll close it. But video team is aware of the issue.

Thanks for taking the time to report the issue!

**Comment by melMass** [comment]
Are there any updates on this ? As @OpusJoyous stated, everthing is in sync, except when using the recorder....

**Comment by melMass** [comment]
Is there a way to access `recordedFramesCount` ?
