### ISSUE TITLE
Road to release: Recorder bug fixes

### ISSUE THREAD

**Issue by CMI-AdamM** [Unity-Technologies/GenericFrameRecorder#3]
Recorder has a number of bugs which prevent it from being released just yet.

It needs further testing - this is not a complete list.

- Only one openEXR method seems to work, the other renders black
- Frame-range setting doesn't seem to work with multiple Timelines in scene
- Single frame number render does not seem to work with multiple Timelines in scene

**Comment by jasonm-unity** [comment]
qa ready

**Comment by jasonm-unity** [comment]
implementation limitation for timeline: one frame recording will not work as the timeline send a destroy event Before EndOfFrame event is reached.

**Comment by spaceemotion** [comment]
Not sure if I should open up a new issue for this, but I just noticed this: https://github.com/Unity-Technologies/GenericFrameRecorder/blob/master/source/FrameRecorder/Recorders/ImageRecorder/Engine/ImageRecorderSettings.cs#L7

The enum is called "PNGRecordeSettings" and not "PNGRecorderSettings" - that's probably a typo, right?

**Comment by jasonm-unity** [comment]
yup, typo. thanks for reporting that back.
