### ISSUE TITLE
Build Error: Plugins colliding with eachother

### ISSUE THREAD

**Issue by justinkmai** [Unity-Technologies/GenericFrameRecorder#31]
##### What happened?
Unity console outputs an error when trying to build:

`Found plugins with same names and architectures, Assets/Unity Technologies/Recorder/Extensions/UTJ/FrameCapturer/Plugins/x86/fccore.dll () and Assets/Unity Technologies/Recorder/Extensions/UTJ/FrameCapturer/Plugins/x86_64/fccore.dll (). Assign different architectures or delete the duplicate.`

##### Is it reproduceable?
Yes.

##### Released package version / tag?
Asset Store RC2 Version 0.1.170901-04.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0p5 Personal (64bit), Mac OS 10.12.5, Android.

**Comment by jasonm-unity** [comment]
I've attempted to replicate the behaviour you are seeing on both PC and mac and I am not seeing the issue.

could you make a simplified project that reproduces the issue and attach it as a package here?

**Comment by justinkmai** [comment]
Hey Jason,

I've attached the project here for you to test. Thanks!

[Recorder_Build_Error.zip](https://github.com/Unity-Technologies/GenericFrameRecorder/files/1299849/Recorder_Build_Error.zip)

**Comment by jasonm-unity** [comment]
update: was able to repro issue. 
Fix should land this week.

**Comment by justinkmai** [comment]
@jasonm-unity great, thanks!

**Comment by jasonm-unity** [comment]
issue fixed in source code. will take a week or two to be updated on asset store

**Comment by jasonm-unity** [comment]
fixed in next release: 0.2.0016+
