### ISSUE TITLE
[v0.2] Recording with resolution other than "Window" gives an error

### ISSUE THREAD

**Issue by JacobSmaga** [Unity-Technologies/GenericFrameRecorder#32]
Starting recording and using any resolution other than "Window" gives an error, If resolution is set to Window and game view resolution is set manually everything works as expected.

![1884318374b9b34f9ed6e126a6215cef](https://user-images.githubusercontent.com/11807714/30240555-ef30d758-9572-11e7-9c11-b80a5b7d2c74.png)

Using 2017.2.0b10

**Comment by JacobSmaga** [comment]
I've used every single version of Recorder. I never had this problem, now when I'm trying to render a movie with resolution other than "Window" i see this:

![fdf68760944b0046d43106a51f3cf952](https://user-images.githubusercontent.com/11807714/30328905-0f413db6-97d1-11e7-8ef8-55fddcba7bcc.png)

Strange thing is that it only happens in a project that used other Recorder builds, in a empty project there is no errors.

**Comment by JacobSmaga** [comment]
Deleting and re-importing Recorder doesn't fix the problem.

**Comment by jasonm-unity** [comment]
Q: if you 1st restart the editor, then delete the recorder directory, does it still occur?
Any chance you can attach a stripped down version of the project that has the error?

**Comment by JacobSmaga** [comment]
A: Still happens.
I don't know why but i don't get this error in empty project, Could i just sent you my main project? (It's around 1GB size) Just send me your email address.

**Comment by jasonm-unity** [comment]
that's too large for email. can you try attaching here? I've no idea what the Github attachement size limit is.

**Comment by JacobSmaga** [comment]
I don't really want to upload my private project here, I wanted your email so i could upload it to Dropbox or some cloud and send you the link privately.

**Comment by jasonm-unity** [comment]
I sent you a msg on the unity forum, for email privacy.

**Comment by JacobSmaga** [comment]
Issue fixed.
