### ISSUE TITLE
Facing problem in recording

### ISSUE THREAD

**Issue by sv955** [Unity-Technologies/GenericFrameRecorder#33]
Facing problem in recording 5K and 8K video recording.

**Comment by jasonm-unity** [comment]
please provide: 
- Hardware spec of machine
- os
- recorder settings.

**Comment by sv955** [comment]
Laptop series : https://www.asus.com/in/ROG-Republic-Of-Gamers/ROG-GX700VO/
RAM : 64 GB
Graphics : 8 GB Graphics card GTX 980
Windows : Windows 10 updated
Recorder setting : Resolution X4320_8k, Target fps : NTSC (29.9)

**Comment by jasonm-unity** [comment]
hum, re-reading the issue, what do you mean by "Facing problem"?
Also, does the console's output log contain any warnings or errors?

**Comment by jasonm-unity** [comment]
mp4 upper limit is 4k. (format specs)
added console errors to inform about that.
webm on the other hand, support up to 16k (but unity does not, 8k max)
