### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'fccore'

### ISSUE THREAD

**Issue by FreakTheMighty** [Unity-Technologies/GenericFrameRecorder#34]
##### What happened?
On iOS when I begin recording I get this error:
```
DllNotFoundException: Unable to load DLL 'fccore': The specified module could not be found.
```
I've tried adding the binary as an embedded binary is xcode, but then I get this error on build:

```
/arkitscene.app/PlugIns/fccore.bundle: unsealed contents present in the bundle root
Command /usr/bin/codesign failed with exit code 1
```
##### Is it reproduceable?
Yes
##### Released package version / tag?
v0.2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
iOS

**Comment by jasonm-unity** [comment]
Video recording: Editor only for now. Standalone within reach for 2018.2. Low-hanging for iOS and other Microsoft platforms as they piggy-back on existing implementations.

**Comment by jasonm-unity** [comment]
Q: How did you trigger the recording? iOS is not supported by the video recorder, so you should have gotten an error in the console that says: Recorder xyz does not support current platform"

you should not be getting a DllNotFoundException!

**Comment by jasonm-unity** [comment]
closing issue, lacking repro steps.
