### ISSUE TITLE
Capture alpha

### ISSUE THREAD

**Issue by kukuhbasuki** [Unity-Technologies/GenericFrameRecorder#41]
How to use "capture alpha" feature?

**Comment by jasonm-unity** [comment]
not sure what you mean by your question?
encoders that support alpha have a check box that stores the alpha.
if you import the result back into unity, some formats will have the option to treat alpha as transparency (importer settings)

**Comment by haywirephoenix** [comment]
I am also struggling to figure out if the Capture Alpha setting can be used to render transparent background png sequences, are there particular settings for the camera clear flags?

**Comment by jasonm-unity** [comment]
In the camera inspector, change clear flags to "Solid color". Just below, in the UI, the colored rectangle allows you to set the clear color. 

By default, it's dark blue and transparent: the black line under the color picker indicates the opacity level, black=fully transparent and white = fully opaque.

**Comment by haywirephoenix** [comment]
Thanks for the reply. 

I tried this in the beginning but it seems to ignore the alpha value. I usually run the editor in forced opengl mode but just tried dx mode same result. Could it be because I'm using culling?

**Comment by jasonm-unity** [comment]
could you make a  test project that reproduces your problem and upload it?

**Comment by haywirephoenix** [comment]
empty project works! It was post processing affecting it. Thanks!

**Comment by jasonm-unity** [comment]
cool :)

**Comment by President-Q** [comment]
So we can't capture alpha with Post Processing ?

**Comment by sneha-badlani** [comment]
how can I export Png sequences from particle system of unity?
