### ISSUE TITLE
Animation Recorder: UI is broken if the record session generates errors

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#43]
We can repro by trying to record a custom script component.

Once we start the recording session, as soon as the console generates error, we'll lose the FrameRecorder UI while in play mode.

we'll need to manually stop the play mode, then the FR UI comes back but the "Start Recording" button will now display "Stop Recording" and we'll be grayed out. We need to close the TAB and reopen the FR to use it again.

**Comment by jasonm-unity** [comment]
added protection against recorders generated exceptions destabilizing recording session & UI.
custom scripts remain unsupported by animation recorder.
