### ISSUE TITLE
Animation Recorder: Recording an "Animator" controller generates 80 errors in the console

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#44]
Trying to record the Animator component will generates a set of 80 errors once we try to show the asset in the inspector.

1. Record a session on Animator
2. Stop the record session
3. Browse to the generated anim clip
4. Once we select the asset, errors are printed in the console

Then any subsequent record on an animator will generate the same errors when we start recording.

**Comment by romainf-unity** [comment]
Issue Tracker link: https://issuetracker.unity3d.com/issues/animation-recorder-error-in-console-when-recording-custom-or-third-party-component

**Comment by jasonm-unity** [comment]
unity issue. closing it here.
