### ISSUE TITLE
Cannot Remove from Project

### ISSUE THREAD

**Issue by warethis-dev** [Unity-Technologies/GenericFrameRecorder#47]
##### What happened?
Removed it, keeps re-importing itself
##### Is it reproduceable?
every single time I delete it
##### Released package version / tag?
v0.1 Recorder
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.2.0f3, Windows 10

**Comment by jasonm-unity** [comment]
what exactly are you deleting?

**Comment by warethis-dev** [comment]
It was my error, sorry. I had a file open at the time and didn't realize it.
