### ISSUE TITLE
FileName hava wrong hour number in PM?

### ISSUE THREAD

**Issue by KumoKyaku** [Unity-Technologies/GenericFrameRecorder#49]
##### What happened?
The name of the file that is automatically generated in the afternoon is not correct，maybe。
![20171204132324](https://user-images.githubusercontent.com/15962980/33537763-514b2a74-d8f8-11e7-9042-770afb68185c.png)

![qq 20171204131616](https://user-images.githubusercontent.com/15962980/33537784-6cf5c5ae-d8f8-11e7-9975-3338bb3bcf56.png)

![qq 20171204131741](https://user-images.githubusercontent.com/15962980/33537787-736d3444-d8f8-11e7-8637-98fef3180542.png)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

**Comment by jasonm-unity** [comment]
yup, that's a bug. fix available in > 0.2.0018
