### ISSUE TITLE
Camera Viewport rect streched in the output if rendered individually

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#50]
##### What happened?
Having a setup of two camera with different viewport rect, if I record the view using tagged camera to only output one of my two cameras, the output will stretch the only camera I recorded to the resolution set in the recorder.

##### Is it reproduceable?
1. Create two cameras in your scene
2. Set different tag to both cameras (e.g: MainCamera and Ground)
3. Set the viewport rect of the camera to be side by side
  - MainCamera -> x=0 y=0 w=0.5 h=1
  - Ground -> x=0.5 y=0 w=0.5 h=1
4. Set the recorder's input source to use TaggedCamera and set the tag to be "Ground"
5. Record with these settings

Result:
The output will have the Ground camera stretched to the resolution chosen in the settings.
I would expect the left half of the output to be black and right half to keep its ratio.

**Comment by jasonm-unity** [comment]
limitation of that input method. added a warning message to inform user that output quality will be degraded.
Adding for 0.2.0.0024
