### ISSUE TITLE
Animation recorder: UI messed up when we add an object to record

### ISSUE THREAD

**Issue by JoelFortin** [Unity-Technologies/GenericFrameRecorder#51]
##### What happened?
The UI is broken when we click on the "Add Object To Record" button
The new "Object Recorder" section appears but is empty and there is an error in the console
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.SortedDictionary`2[System.Int32,UnityEditor.Recorder.RTInputSelector+InputGroup].get_Item (Int32 key)

##### Is it reproduceable?
1. Open the Animation recorder window
2. Click on the "Add Object To Record" button

##### Released package version / tag?
Recorder package 0.2.0.0022

**Comment by jasonm-unity** [comment]
fixed in build 0.2.0.0023
