### ISSUE TITLE
I can Only export Image Sequences.

### ISSUE THREAD

**Issue by eldaville** [Unity-Technologies/GenericFrameRecorder#52]
How Am I supposed to record a video file with audio?

I've seen some people selecting an option to record video but I only have "Image Sequence" as option.

and when I hit Tools/Recorder/About... / View User Manual

it can't find the "Recorder_install.pdf" file that it's trying to open.

So how do I export audio and video? not only images?

**Comment by JacobSmaga** [comment]
Exporting video with audio is in Unity +2017.3.
Update your recorder to the newest one: https://github.com/Unity-Technologies/GenericFrameRecorder/releases/tag/0.2.0023
Recording video should be under Unity/Movie
[https://i.gyazo.com/34f29571f66401c6c6d7ed261dfd16d3.png](url)

**Comment by jasonm-unity** [comment]
are you using the asset store package or one of the released packages from git hub?

**Comment by eldaville** [comment]
I'm using the one found here on Git Hub... didn't knew there was one version in the store.

**Comment by jasonm-unity** [comment]
and which version of unity are you using? Also, there are two recorders that output MP4/WebM files. you want to select the Unity/Movie, as Jacob commented.

fyi: Sound capture is not supported prior to unity 2017.3.

**Comment by jasonm-unity** [comment]
oh, and the latest version of git hub is much more recent than whats on the asset store...

**Comment by brnkhy** [comment]
I might be missing something here but I think I'm having a similar issue. I used it (from github) on 2017.1 many times before to record videos. But now I tried to take a shot again and all I'm getting is Image Sequence 

![unity_2017-12-20_12-24-25](https://user-images.githubusercontent.com/1465390/34200050-bfac1520-e580-11e7-9f31-68a7c7da05b5.png)

Now even if I open the old projects, which I recorded before, I only get image sequence.

What happened in between?
- if I remember correctly I installed windows 10 updates for VR (this broke codecs maybe?)
- installed 2017.3 in a new folder

I probably should have tried restarting pc before posting this actually, I'll do that and edit this if it fixes the issue.

**Comment by jasonm-unity** [comment]
yes, going the package route will make your life much easier.

**Comment by eldaville** [comment]
I'm still having the same problem in 2017.3

I'm importing the folder directly, where is the package?

**Comment by jasonm-unity** [comment]
what do you mean: "importing the folder" directly? 
if all you need is to Use the recorder, then you should simply Import the latest released package.
