### ISSUE TITLE
[Recorder] MovieRecorder package is reimported on every assembly reload

### ISSUE THREAD

**Issue by Justiss50** [Unity-Technologies/GenericFrameRecorder#60]
To reproduce:
1. Create a new project
2. Download latest recorder package and import it https://www.assetstore.unity3d.com/en/#!/content/94079
3. Enter play mode

Expected: 'Importing MovieRecorder...' message won't be shown after importing asset package or entering play mode
Actual: While entering play mode, importing package progress dialog will show up and produce log message to console

Reproduced: 2017.3.0p2, 2018.1.0b2, 2018.2.0a1
Nor reproducible: 2017.1.2p4, 2017.2.1p1

If there will be any questions, please contact @justinasp :)

**Comment by jasonm-unity** [comment]
fixed.
