### ISSUE TITLE
`Menu' does not contain a definition for `SetChecked'

### ISSUE THREAD

**Issue by Bhalut** [Unity-Technologies/GenericFrameRecorder#70]
##### What happened?
Error console.
##### Is it reproduceable?
Assets/GenericFrameRecorder-master/source/FrameRecorder/Core/Engine/Verbose.cs(45,18): error CS0117: `Menu' does not contain a definition for `SetChecked'
##### Released package version / tag?
February 28 / 2018
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.f1

**Comment by Rich-O4D** [comment]
In our case we had another plugin with a menu.cs which wasn't using a namespace and clashing with the Recorder Menu call. Really the Recorder Menu call should also be using namespace e.g UnityEngine.Recorder.Menu

**Comment by ghost** [comment]
I don't have UnityEngine.Recorder.Menu

**Comment by SaiGaneshRachamadugu** [comment]
how to fix this issue @Bhalut
