### ISSUE TITLE
Command Buffered Camera hardcodes full opacity.

### ISSUE THREAD

**Issue by Dominique-Unity** [Unity-Technologies/GenericFrameRecorder#8]
This line in the CommandFrameBufer shader causes the captured image's alpha to be ignored and replaced by full opacity:

https://github.com/Unity-Technologies/GenericFrameRecorder/blob/master/source/FrameRecorder/Inputs/CBRenderTexture/Shaders/CopyFrameBuffer.shader#L53

When the Camera used for recording has its Clear Flags set to "Solid Color", the Background color's alpha component can be set by the user and ends up in the rendered image. But the shader overwrites this color (possibly to overcome the fact that the default alpha value of this color is 0=fully transparent?).

Commenting-out this line in the shader causes recording with alpha to work as expected.

**Comment by i-saint** [comment]
> (possibly to overcome the fact that the default alpha value of this color is 0=fully transparent?)

I think this is the case (but not sure. this part was written over a year ago), and I think it is safe to change. I changed locally and tested. it seems no problem.

**Comment by jasonm-unity** [comment]
added UI option to preserve transparency.
